default:
  image:
    name: hashicorp/terraform
    pull_policy: if-not-present
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/ivanopulo/Downloads/jammy-server-cloudimg-amd64.img"
  tags:
    - docker

  before_script:
    - terraform init
  cache:
    key: terraform
    paths:
      - .terraform

stages:
  - validate
  - plan
  - apply
  - destroy

tf-validate:
  stage: validate
  script:
    - terraform validate
    - terraform fmt
    - terraform fmt -check

tf-plan:
  stage: plan
  needs: ["tf-validate"]
  script:
    - terraform plan

tf-apply:
  image: registry.gitlab.com/ivan.yakimenko.win/gitops:terraform-plus-cdrkit
  stage: apply
  needs: ["tf-plan"]
  tags:
    - docker
  script:
    - terraform apply -auto-approve

tf-destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual
