stages:
  - terraform

tf-validate:
  stage: terraform
  image:
    name: hashicorp/terraform
    pull_policy: if-not-present
    entrypoint: [""]
  tags:
    - docker
  before_script:
    - terraform init
  script:
    - terraform validate
    - terraform fmt -check

tf-build:
  stage: terraform
  needs: ["tf-validate"]
  image:
    name: hashicorp/terraform
    entrypoint: [""]
    pull_policy: if-not-present
  tags:
    - docker
  before_script:
    - terraform plan
  script:
    - terraform apply -auto-approve
